bookstore/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
path('register/', views.register, name='register'),
path('login/', views.login, name='login'), 
path('logout/', views.logout, name='logout'),
]

bookstore/bookstore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
   path('order/', include('order.urls', namespace='order')),
    re_path('.*', views.main),
]

bookstore/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login, name='login'),
    path('about/', views.about, name='about'),
    path('login/', views.login, name='login'),
    path('aboutbookstore/', views.aboutbookstore, name='aboutbookstore'),
    path('personal/', views.personal, name='personal'),
    path('new/', views.new, name='new'),
    path('hot/', views.hot, name='hot'),
    path('34off/', views.saleoff, name='34off'),
    path('title1/', views.title1, name='title1'),
    path('title2/', views.title2, name='title2'),
    path('title3/', views.title3, name='title3'),
    path('title4/', views.title4, name='title4'),
    path('book1/', views.book1, name='book1'),
    path('book2/', views.book2, name='book2'),
    path('book3/', views.book3, name='book3'),
    path('book4/', views.book4, name='book4'),
]

bookstore/order/urls.py
from django.urls import path
from order import views


app_name = 'order'
urlpatterns = [
    path('order/', views.order, name='order'),
    path('order/check/', views.ordercheck, name='ordercheck'),
]

bookstore/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    fullName = models.CharField(max_length=128)
    website = models.URLField(blank=True, null=True)
    address = models.CharField(max_length=128, blank=True, null=True)

    def __str__(self):
        return self.fullName + ' (' + self.username + ')'

bookstore/main/models.py
from django.db import models

# Create your models here.

bookstore/order/models.py
from django.db import models

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=128)
    number = models.CharField(max_length=128) 
    title = models.CharField(max_length=128)
    amount = models.CharField(max_length=128)


    def __str__(self):
        return self.title

bookstore/account/forms.py
from django import forms
from account.models import User


class UserForm(forms.ModelForm):
    username = forms.CharField(label='帳號')
    password = forms.CharField(label='密碼', widget=forms.PasswordInput())
    password2 = forms.CharField(label='確認密碼', widget=forms.PasswordInput())
    fullName = forms.CharField(label='姓名', max_length=128)
    address = forms.CharField(label='住址', max_length=128)
    
    class Meta:
        model = User
        fields = ['username', 'password', 'password2', 'fullName', 'address']

    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password and password2 and password!=password2:
            raise forms.ValidationError('密碼不相符')
        return password2

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.set_password(user.password)
        if commit:
            user.save()
        return user

bookstore/order/forms.py
from django import forms
from order.models import Product


class ProductForm(forms.ModelForm):
    name = forms.CharField(label='收件人')
    title = forms.ChoiceField(label='書　名',choices=[(0,'請選擇書名'),('傲慢與偏見 $284','傲慢與偏見'),('被討厭的勇氣  $237','被討厭的勇氣'),('福爾摩斯全集(套書) $980','福爾摩斯全集(套書)'),('HarryPotter $284','HarryPotter')])
    amount = forms.CharField(label='數　量')
    number = forms.CharField(label='連絡電話')
    
    
    class Meta:
        model = Product
        fields =  ['id','name','title','amount','number']

bookstore/account/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from account.forms import UserForm


def register(request):
    '''
    Register a new user
    '''
    template = 'account/register.html'
    if request.method == 'GET':
        return render(request, template, {'userForm':UserForm()})

    # POST
    userForm = UserForm(request.POST)
    if not userForm.is_valid():
        return render(request, template, {'userForm':userForm})

    userForm.save()
    return redirect('main:main')

def login(request):
    '''
    Login an existing user
    '''
    template = 'account/login.html'
    if request.method == 'GET':
        return render(request, template)

    # POST
    username = request.POST.get('username')
    password = request.POST.get('password')
    if not username or not password:    # Server-side validation
        messages.error(request, '請填資料')
        return render(request, template)

    user = authenticate(username=username, password=password)
    if not user:    # authentication fails
        messages.error(request, '登入失敗，請再輸入一次')
        return render(request, template)

    # login success
    auth_login(request, user)
    return redirect('main:main')


def logout(request):
    '''
    Logout the user
    '''
    auth_logout(request)

    return redirect('main:main')


bookstore/main/views.py
from django.shortcuts import render



def main(request):
    '''
    Render the main page
    '''
    return render(request, 'main/main.html')

def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

def login(request):
    '''
    Render the about page
    '''
    return render(request, 'main/login.html')

def aboutbookstore(request):
    '''
    Render the about page
    '''
    return render(request, 'main/aboutbookstore.html')

def personal(requset):
    return render(requset,'main/personal.html')

def new(requset):
    return render(requset,'main/new.html')

def hot(requset):
    return render(requset,'main/hot.html')

def saleoff(requset):
    return render(requset,'main/34off.html')

def title1(requset):
    return render(requset,'main/title1.html')

def title2(requset):
    return render(requset,'main/title2.html')

def title3(requset):
    return render(requset,'main/title3.html')

def title4(requset):
    return render(requset,'main/title4.html')

def book1(requset):
    return render(requset,'main/book1.html')

def book2(requset):
    return render(requset,'main/book2.html')

def book3(requset):
    return render(requset,'main/book3.html')

def book4(requset):
    return render(requset,'main/book4.html')



bookstore/order/views.py
from django.shortcuts import render, redirect
from order.models import Product
from order.forms import ProductForm

def order(request):
    template = 'order/order.html'
    if request.method == 'GET':
        return render(request, template, {'productForm':ProductForm()})

    # POST
    productForm = ProductForm(request.POST)
    if not productForm.is_valid():
        return render(request, template, {'productForm':productForm})

    productForm.save()
    return redirect('order:ordercheck')

def ordercheck(request):
    products = Product.objects.all().order_by('-id')[:1] 
    context = {'products':products}
    return render(request,'order/ordercheck.html',context)


bookstore/main/templates/main/book1.html
<!doctype html> 
{% load staticfiles %}
<html> 
<head> 
<meta charset="utf-8"> 
<link rel="stylesheet" href="{% static 'main/css/share.css' %}">
<link rel="stylesheet" href="{% static 'main/css/book.css' %}">
</head> 
<body> 

<div id="wrapper">
  <nav>
    <ul class="menu">
      <li class="menu-sort"><a href="{% url 'main:main' %}" style="text-decoration:none;">首頁</a></li>．
        {% if user.is_authenticated %}
      <li class="menu-sort"><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></li>．
        {% else %}
      <li class="menu-sort"><a href="{% url 'account:login' %}"style="text-decoration:none;">登入</a></li>．
      <li class="menu-sort"><a href="{% url 'account:register' %}"style="text-decoration:none;">註冊</a></li>．
        {% endif %}
      <li class="menu-sort"><a href="{% url 'main:aboutbookstore' %}"style="text-decoration:none;">關於我們</a></li>
    </ul>
  </nav>
 
  <header>
    <a href="{% url 'main:main' %}"><img src = "{% static 'main/img/bookstore02.jpg' %}" alt="bookstore" width = "350" ></a>
  </header>
  
<div>
  <ul class="top">
    <li class="top-sort"><a href="{% url 'main:new' %}"style="text-decoration:none;">新品推薦</a></li>．
    <li class="top-sort"><a href="{% url 'main:hot' %}"style="text-decoration:none;">暢銷書榜</a></li>．
    <li class="top-sort"><a href="{% url 'main:34off' %}"style="text-decoration:none;">今日66折</a></li>
  </ul>
</div>
  
  <div id="sup"><img src = "{% static 'main/img/hr01.jpg' %}" alt="hr" width = 100%></div>
  <aside>
  <p class="shopmenu-title">購物分類</p>
  <p class="shopmenu" >&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >中文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title1' %}" style = "text-decoration:none;">經典文學</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title2' %}" style = "text-decoration:none;">心理勵志</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title3' %}" style = "text-decoration:none;">推理文學</a></li>
      </ul>
    <p class="shopmenu" font-size: 15px>&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >英文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title4' %}" style = "text-decoration:none;">科幻小說</a></li>
      </ul>
  </aside>
  <div id="content">  
    <div id="photo">
    <img class="photo-img" src="{% static 'main/img/book1.jpg' %}">
    </div>
    <div id="author">
      <p><b>傲慢與偏見</b></p>
            作者： 珍‧奧斯汀<br>
            原文作者： Jane Austen<br>
            譯者： 柯乃瑜<br>
            出版社：木馬文化<br>
            出版日期：2018/12/12<br>
            語言：繁體中文<br>
            定價：360元<br>
            優惠價：79折284元
      <button><a href ="{% url 'order:order' %}"style = "text-decoration:none;">購買</a></button>

    </div>
    <div id="about" style="overflow-y:scroll">
      <h3>內容簡介</h3><hr>
      <p>　　傲嬌少爺X聰明小姐的二見鍾情</p>

　　珍•奧斯汀改編最多、評價最高的作品<br>
　　愛上了，才知道放下傲慢並不難<br>
　　戀上了，所有的偏見都襯得優點閃耀光芒

　　<p>　　「你是怎麼開始的？我可以理解你一旦愛上我，當然就會非常愛我，可你一開始怎麼會愛上我？」<br>
　　「我說不出感情生根的確切時間、地點、表情或言語。已經太久了。等我意識到自己已經愛上妳，早就開始很久了。」<br>
　　「你先前成功抗拒了我的美貌，至於我的禮貌，我對總是近乎不客氣，每次跟你說話都只想故意讓你不好過。說實話，你其實是欣賞我的魯莽吧？」<br>

　　「我確實欣賞妳活潑的個性。」<br>

　　「你就老實說是魯莽吧。根本就差不多了。事實是，你早就厭倦了那些客套、順從以及過度的殷勤。你受夠了那些總是只對你說話、只看著你而且只尋求你稱許的女人。我能引起你的興趣，是因為我跟她們完全不同。要你真是個討厭鬼，一定會很厭惡這樣的我；但儘管你那麼努力掩飾，你的感覺總是高貴公正，在你心裡，你著實唾棄那些苦心追求你的人。好啦，我替你省去了說明的麻煩，而且說真的，這樣一想還滿有道理的。畢竟你其實根本不知道我真正的優點，但是熱戀的時候也沒人會想到這個。」<br>

    　　「如果說，羅蘭．巴特用一本《戀人絮語》揭露愛情的語言結構與表意系統，從此沒有先於語言的戀人，沒有先於符號的愛情，那麼，《傲慢與偏見》就是獨屬於珍迷的戀人絮語。在珍迷的世界中，沒有先於達西先生的男人，沒有先於《傲慢與偏見》的愛情。所有的愛情與慾望，都只能在珍．奧斯汀的語言與符號中產生意義。」——施舜翔<br></p>

      <h3>本書特色</h3><hr>

　　<p>　　1. 全新台灣譯者中譯<br>

　　2. 參照哈佛大學註解版等中外相關文獻，提供最新穎、全面而當代化的中文註解<br>

　　3. 系列總導讀：高瑟濡（台灣大學外文系教授）──社會與人性的觀察家：談珍‧奧斯汀的長篇小說，馮品佳（交通大學外文系講座教授，中研院歐美所合聘研究員）──我們的珍‧奧斯汀<br>

　　4. 台灣當代作家專文推薦：施舜翔（作家，文化評論人）──珍‧奧斯汀的妹妹們：一段《傲慢與偏見》的當代再現史<br>

　　5. 精采譯後記<br>

    　　6. 融合經典與現代，風格統一的包裝：知名平面設計師 莊謹銘 操刀「假使羅曼史小說有祖譜的話，那珍奧斯汀肯定是祖師奶奶。」——李桐豪（作家）<br></p>

      <h3>好評推薦</h3><hr>

　　<p>「在欲望流竄的當代社會，奧斯汀筆下各種發乎情而又止乎禮的感情篇章或許更能引人入勝。」——馮品佳（交通大學外文系講座教授）<br>

　　「一切的愛情故事從珍奧斯汀的地平線上起跑，跑，不停跑，世界上所有嚮往愛情的女孩都在奔跑……」——陳栢青（作家）<br>

　　「珍．奧斯汀是我的使命。過去我一直嘗試在電影中把社會諷刺和家庭倫理劇融合起來；如今我理解到，長久以來我所做的，其實就是像珍．奧斯汀那樣的作品，只是沒意識到而已。」——李安（電影《理性與感性》導演，節錄自Newsweek專訪）<br>

　　「有些書能夠表達對生活的看法，而且說得非常清楚，比我們自己說得都清楚。生活中的尷尬、苦惱、嫉妒、罪惡感，這一切經過奧斯汀之手一一呈現在我們眼前，使我們以一種神奇的方式看清自己。」——艾倫．狄波頓（英國知名作家）<br>

　　「奧斯汀採用反諷的手法，把莎士比亞那種對人性的刻畫提升到爐火純青的地步。她非凡的喜劇天賦，自莎士比亞以降無人能出其右。」——哈洛卜倫（《西方正典》作者）<br>

　　「奧斯汀小姐描述了日常生活中的平凡事物，人們在日常生活中的活動和情感；故事中沒有什麼大事，但是你讀完一頁會趕緊翻到下一頁，希望知道接下來會發生什麼事；下頁讀完，依舊沒什麼大事，可是你會帶著同樣迫切的心情往下閱讀。」——威廉．薩默塞特．毛姆（英國小說大師）<br>

　　「我是珍迷，所以一提到她，我就會笨嘴笨舌的。」——E. M. 佛斯特（英國小說大師）<br>

    「我從七歲起就是珍迷。」——綺拉奈特莉（英國女星，節錄自媒體專訪）<br></p>
    </div>
  </div>
  <footer></footer>
</div> <!-- wrapper -->

</body>
</html>

bookstore/main/templates/main/book4.html
<!doctype html> 
{% load staticfiles %}
<html> 
<head> 
<meta charset="utf-8"> 
<link rel="stylesheet" href="{% static 'main/css/share.css' %}">
<link rel="stylesheet" href="{% static 'main/css/book.css' %}">
</head> 
<body> 

<div id="wrapper">
  <nav>
    <ul class="menu">
      <li class="menu-sort"><a href="{% url 'main:main' %}" style="text-decoration:none;">首頁</a></li>．
        {% if user.is_authenticated %}
      <li class="menu-sort"><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></li>．
        {% else %}
      <li class="menu-sort"><a href="{% url 'account:login' %}"style="text-decoration:none;">登入</a></li>．
      <li class="menu-sort"><a href="{% url 'account:register' %}"style="text-decoration:none;">註冊</a></li>．
        {% endif %}
      <li class="menu-sort"><a href="{% url 'main:aboutbookstore' %}"style="text-decoration:none;">關於我們</a></li>
    </ul>
  </nav>
 
  <header>
    <a href="{% url 'main:main' %}"><img src = "{% static 'main/img/bookstore02.jpg' %}" alt="bookstore" width = "350" ></a>
  </header>
  
<div>
  <ul class="top">
    <li class="top-sort"><a href="{% url 'main:new' %}"style="text-decoration:none;">新品推薦</a></li>．
    <li class="top-sort"><a href="{% url 'main:hot' %}"style="text-decoration:none;">暢銷書榜</a></li>．
    <li class="top-sort"><a href="{% url 'main:34off' %}"style="text-decoration:none;">今日66折</a></li>
  </ul>
</div>
  
  <div id="sup"><img src = "{% static 'main/img/hr01.jpg' %}" alt="hr" width = 100%></div>
  <aside>
  <p class="shopmenu-title">購物分類</p>
  <p class="shopmenu" >&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >中文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title1' %}" style = "text-decoration:none;">經典文學</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title2' %}" style = "text-decoration:none;">心理勵志</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title3' %}" style = "text-decoration:none;">推理文學</a></li>
      </ul>
    <p class="shopmenu" font-size: 15px>&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >英文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title4' %}" style = "text-decoration:none;">科幻小說</a></li>
      </ul>
  </aside>
  <div id="content">  
    <div id="photo">
    <img class="photo-img" src="{% static 'main/img/book4.jpg' %}">
    </div>
    <div id="author">
      <p><b>Harry Potter and the Cursed Child - Parts One and Two: The Official Script Book of the Original West End Production Special Rehe</b></p>
            作者： Rowling,J.K./ Thorne,JackTiffany,John<br>
            出版社：Arthur a Levine<br>
            出版日期：2016/07/31<br>
            語言：英文<br>
            定價：1050元<br>
            優惠價：693元
      <button><a href ="{% url 'order:order' %}"style = "text-decoration:none;">購買</a></button>
    </div>
    <div id="about" style="overflow-y:scroll">
      <h3>內容簡介</h3><hr>
　      　第一部哈利波特舞台劇<br>
　　 正宗哈利波特第8集《哈利波特：被詛咒的孩子》<br>
　　 以J.K. 羅琳最新的原創故事改編。2016年中全球首演劇本<br>
 
      <p>　　19年過去了，哈利‧波特不僅是名人，更成為一名巫師、魔法部的超時工作員工、一名丈夫、及三個孩子的父親。雖然哈利一直拒絕屈服於他的命運，但他最小的兒子阿不思，仍然需要學習面對家族的傳統及盛名。他們父子必須共同面對那個令人不安的事實：有時，黑暗來自最意想不到的地方。</p>
＜Ｂｏｏｋｓｔｏｒｅ編譯＞
    </div>
  </div>
  <footer></footer>
</div> <!-- wrapper -->

</body>
</html>

bookstore/main/templates/main/hot.html
<!doctype html> 
{% load staticfiles %}
<html> 
<head> 
<meta charset="utf-8"> 
<link rel="stylesheet" href="{% static 'main/css/share.css' %}">
<link rel="stylesheet" href="{% static 'main/css/product.css' %}">
</head> 
<body> 

<div id="wrapper">
  <nav>
    <ul class="menu">
      <li class="menu-sort"><a href="{% url 'main:main' %}" style="text-decoration:none;">首頁</a></li>．
        {% if user.is_authenticated %}
      <li class="menu-sort"><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></li>．
        {% else %}
      <li class="menu-sort"><a href="{% url 'account:login' %}"style="text-decoration:none;">登入</a></li>．
      <li class="menu-sort"><a href="{% url 'account:register' %}"style="text-decoration:none;">註冊</a></li>．
        {% endif %}
      <li class="menu-sort"><a href="{% url 'main:aboutbookstore' %}"style="text-decoration:none;">關於我們</a></li>
    </ul>
  </nav>
 
  <header>
    <a href="{% url 'main:main' %}"><img src = "{% static 'main/img/bookstore02.jpg' %}" alt="bookstore" width = "350" ></a>
  </header>
  
<div>
  <ul class="top">
    <li class="top-sort"><a href="{% url 'main:new' %}"style="text-decoration:none;">新品推薦</a></li>．
    <li class="top-sort"><a href="{% url 'main:hot' %}"style="text-decoration:none;">暢銷書榜</a></li>．
    <li class="top-sort"><a href="{% url 'main:34off' %}"style="text-decoration:none;">今日66折</a></li>
  </ul>
</div>
  
  <div id="sup"><img src = "{% static 'main/img/hr01.jpg' %}" alt="hr" width = 100%></div>
  <aside>
  <p class="shopmenu-title">購物分類</p>
  <p class="shopmenu" >&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >中文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title1' %}" style = "text-decoration:none;">經典文學</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title2' %}" style = "text-decoration:none;">心理勵志</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title3' %}" style = "text-decoration:none;">推理文學</a></li>
      </ul>
    <p class="shopmenu" font-size: 15px>&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >英文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title4' %}" style = "text-decoration:none;">科幻小說</a></li>
      </ul>
  </aside>
  <div id="content">  
    <h2>　暢銷書榜</h2>
    <div id="product1">
    <img class="product2-img" src="{% static 'main/img/book1.jpg' %}">
    </div>
    <div id="product2">
    <img class="product3-img" src="{% static 'main/img/book3.jpg' %}">
    </div>
    <div id="product3"> 
    </div>
    <div id="introduce1"><a href="{% url 'main:book1' %}" style = "text-decoration:none;">
    <b>傲慢與偏見</b><br>
    <p>作者：珍．奧斯汀</p>
    優惠價：79折284元
    </a></div>
    <div id="introduce2"><a href="{% url 'main:book3' %}" style = "text-decoration:none;">
    <b>福爾摩斯探案全集(套書)</b><br>
    <p>作者：柯南道爾</p>
    優惠價：7折980元
    </a></div>
    <div id="introduce3">
    </div>
  </div>
  <footer></footer>
</div> <!-- wrapper -->

</body>
</html>

bookstore/main/templates/main/messages.html
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}

bookstore/main/templates/main/new.html
<!doctype html> 
{% load staticfiles %}
<html> 
<head> 
<meta charset="utf-8"> 
<link rel="stylesheet" href="{% static 'main/css/share.css' %}">
<link rel="stylesheet" href="{% static 'main/css/product.css' %}">
</head> 
<body> 

<div id="wrapper">
  <nav>
    <ul class="menu">
      <li class="menu-sort"><a href="{% url 'main:main' %}" style="text-decoration:none;">首頁</a></li>．
        {% if user.is_authenticated %}
      <li class="menu-sort"><a href="{% url 'account:logout' %}">登出 ({{ user.username }})</a></li>．
        {% else %}
      <li class="menu-sort"><a href="{% url 'account:login' %}"style="text-decoration:none;">登入</a></li>．
      <li class="menu-sort"><a href="{% url 'account:register' %}"style="text-decoration:none;">註冊</a></li>．
        {% endif %}
      <li class="menu-sort"><a href="{% url 'main:aboutbookstore' %}"style="text-decoration:none;">關於我們</a></li>
    </ul>
  </nav>
 
  <header>
    <a href="{% url 'main:main' %}"><img src = "{% static 'main/img/bookstore02.jpg' %}" alt="bookstore" width = "350" ></a>
  </header>
  
<div>
  <ul class="top">
    <li class="top-sort"><a href="{% url 'main:new' %}"style="text-decoration:none;">新品推薦</a></li>．
    <li class="top-sort"><a href="{% url 'main:hot' %}"style="text-decoration:none;">暢銷書榜</a></li>．
    <li class="top-sort"><a href="{% url 'main:34off' %}"style="text-decoration:none;">今日66折</a></li>
  </ul>
</div>
  
  <div id="sup"><img src = "{% static 'main/img/hr01.jpg' %}" alt="hr" width = 100%></div>
  <aside>
  <p class="shopmenu-title">購物分類</p>
  <p class="shopmenu" >&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >中文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title1' %}" style = "text-decoration:none;">經典文學</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title2' %}" style = "text-decoration:none;">心理勵志</a></li>
        <li class="shopmenu1"><a href="{% url 'main:title3' %}" style = "text-decoration:none;">推理文學</a></li>
      </ul>
    <p class="shopmenu" font-size: 15px>&nbsp;<img src = "{% static 'main/img/shopmenu.jpg' %}" >英文書</p>
      <ul>
        <li class="shopmenu1"><a href="{% url 'main:title4' %}" style = "text-decoration:none;">科幻小說</a></li>
      </ul>
  </aside>
  <div id="content">  
    <h2>　新品推薦</h2>
  <div id="product1">
  <img class="product-img" src="{% static 'main/img/book2.jpg' %}">
  </div>
    <div id="product2">
    </div>
    <div id="product3">
    </div>
    <div id="introduce1"><a href="{% url 'main:book2' %}" style = "text-decoration:none;">
    <b>被討厭的勇氣：自我啟發之父「阿德勒」的教導</b><br>
    <p>作者：岸見一郎，古賀史健</p>
    優惠價：79折237元
    </a></div>
    <div id="introduce2">
    </div>
    <div id="introduce3">
    </div>
  </div>
  <footer></footer>
</div> <!-- wrapper -->

</body>
</html>